///-----------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Template File Name: Exception.cst 
///     Generated: 6/21/2005 3:27:40 PM
/// </autogenerated>
///-----------------------------------------------------------------------------
using System;

namespace UnitTester.BusinessObjects 
{

	/// <summary>
	/// Thrown when you run out of money in your account.
	/// </summary>
	[Serializable]
	public class InsufficientFundsException : Exception 
	{
		#region Constructors

		/// <summary>
		/// Create a InsufficientFundsException Exception.
		/// </summary>
		public InsufficientFundsException() : base() { }

		/// <summary>
		/// Create a InsufficientFundsException Exception.
		/// </summary>	
		/// <param name="msg">A Message describing the details of the exception.</param>
		public InsufficientFundsException(string msg) : base(msg) { }		

		/// <summary>
		/// Create a InsufficientFundsException Exception.
		/// </summary>
		/// <param name="msg">A Message describing the details of the exception</param>
		/// <param name="inner">Details of an inner exception</param>
		public InsufficientFundsException(string msg, Exception inner) : base(msg, inner) { }

		/// <summary>
		/// Create a InsufficientFundsException Exception. 
		/// </summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected InsufficientFundsException(System.Runtime.Serialization.SerializationInfo info, 
			System.Runtime.Serialization.StreamingContext context) : base(info, context) { }

		#endregion

	}
}
