//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ASP {
	using System;
    using System.Collections;
	using System.Collections.Specialized;
	using System.Configuration;
	using System.Text;
	using System.Text.RegularExpressions;
	using System.Web;
	using System.Web.Caching;
	using System.Web.SessionState;
	using System.Web.Security;
	using System.Web.UI;
	using System.Web.UI.WebControls;
	using System.Web.UI.HtmlControls;
	using ASP;
      

	[System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
	public class Generated_aspx : Lifecycle.Generated, System.Web.SessionState.IRequiresSessionState {
          

		
	    protected System.Web.UI.WebControls.Label lblHelloWorld;      
		protected System.Web.UI.WebControls.TextBox txt;
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
      
		private static bool __initialized = false;
		private static object __stringResource;
		private static System.Collections.ArrayList __fileDependencies;


		public Generated_aspx() {
			System.Collections.ArrayList dependencies;
			if ((ASP.Generated_aspx.__initialized == false)) {
				ASP.Generated_aspx.__stringResource = System.Web.UI.TemplateControl.ReadStringResource(typeof(ASP.Generated_aspx));
				dependencies = new System.Collections.ArrayList();
				dependencies.Add("C:\\Projects\\ASP.NET Lifecycle\\Solutions\\Lifecycle\\generated.aspx");
				ASP.Generated_aspx.__fileDependencies = dependencies;
				ASP.Generated_aspx.__initialized = true;
			}
			this.Server.ScriptTimeout = 30000000;
		}
      
		protected override bool SupportAutoEvents {
			get {
				return false;
			}
		}
      
		protected ASP.Global_asax ApplicationInstance {
			get {
				return ((ASP.Global_asax)(this.Context.ApplicationInstance));
			}
		}
      
		public override string TemplateSourceDirectory {
			get {
				return "/lifecycle";
			}
		}
      
		private System.Web.UI.Control __BuildControllblHelloWorld() {
			
			System.Web.UI.WebControls.Label __ctrl;
			__ctrl = new System.Web.UI.WebControls.Label();
			this.lblHelloWorld = __ctrl;
			
			__ctrl.ID = "lblHelloWorld";

			System.Web.UI.IParserAccessor __parser = ((System.Web.UI.IParserAccessor)(__ctrl));
			__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("A Label."));

			return __ctrl;
		}
      
		private System.Web.UI.Control __BuildControltxt() {
			System.Web.UI.WebControls.TextBox __ctrl;
			__ctrl = new System.Web.UI.WebControls.TextBox();
      
			this.txt = __ctrl;

			__ctrl.ID = "txt";

			__ctrl.Text = "A TextBox";

			return __ctrl;
		}
      
		private System.Web.UI.Control __BuildControlForm1() {
			System.Web.UI.HtmlControls.HtmlForm __ctrl;
     
			__ctrl = new System.Web.UI.HtmlControls.HtmlForm();

			this.Form1 = __ctrl;

			__ctrl.ID = "Form1";
      
			__ctrl.Method = "post";
      
			System.Web.UI.IParserAccessor __parser = ((System.Web.UI.IParserAccessor)(__ctrl));
      
			__parser.AddParsedSubObject(
				new System.Web.UI.LiteralControl("\r\n\t\tThis is what a generated page looks like.\r\n\t\t<br>\r\n\t\t"));
      
			this.__BuildControllblHelloWorld();

			__parser.AddParsedSubObject(this.lblHelloWorld);
      
			__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t<br>\r\n\t\t"));

			this.__BuildControltxt();

			__parser.AddParsedSubObject(this.txt);

			__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
      
			return __ctrl;
		}
      
		private void __BuildControlTree(System.Web.UI.Control __ctrl) {

			this.__BuildControlForm1();
      
			System.Web.UI.IParserAccessor __parser = ((System.Web.UI.IParserAccessor)(__ctrl));

			__parser.AddParsedSubObject(this.Form1);

			__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.__Render__control1));
		}
      
		private void __Render__control1(System.Web.UI.HtmlTextWriter __output, System.Web.UI.Control parameterContainer) {
			this.WriteUTF8ResourceString(__output, 0, 408, true);
      
			parameterContainer.Controls[0].RenderControl(__output);
      
			__output.Write("\r\n  </body>\r\n</html>\r\n");
      
	
			Response.Write(;       
			
		}

		protected override void FrameworkInitialize() {
			SetStringResourcePointer(ASP.Generated_aspx.__stringResource, 408);
			this.__BuildControlTree(this);
			this.FileDependencies = ASP.Generated_aspx.__fileDependencies;
			this.EnableViewStateMac = true;
			this.Request.ValidateInput();
		}
      
		public override int GetTypeHashCode() {
			return -652623765;
		}
	}
}
