//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PirateShipConsumer.MyPirateShipFactory {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PirateShip", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PirateShip : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyPirateShipFactory.PirateShipFactorySoap")]
    public interface PirateShipFactorySoap {
        
        // CODEGEN: Generating message contract since element name shipName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuildShip", ReplyAction="*")]
        PirateShipConsumer.MyPirateShipFactory.BuildShipResponse BuildShip(PirateShipConsumer.MyPirateShipFactory.BuildShipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildShipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuildShip", Namespace="http://tempuri.org/", Order=0)]
        public PirateShipConsumer.MyPirateShipFactory.BuildShipRequestBody Body;
        
        public BuildShipRequest() {
        }
        
        public BuildShipRequest(PirateShipConsumer.MyPirateShipFactory.BuildShipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildShipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shipName;
        
        public BuildShipRequestBody() {
        }
        
        public BuildShipRequestBody(string shipName) {
            this.shipName = shipName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildShipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuildShipResponse", Namespace="http://tempuri.org/", Order=0)]
        public PirateShipConsumer.MyPirateShipFactory.BuildShipResponseBody Body;
        
        public BuildShipResponse() {
        }
        
        public BuildShipResponse(PirateShipConsumer.MyPirateShipFactory.BuildShipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildShipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PirateShipConsumer.MyPirateShipFactory.PirateShip BuildShipResult;
        
        public BuildShipResponseBody() {
        }
        
        public BuildShipResponseBody(PirateShipConsumer.MyPirateShipFactory.PirateShip BuildShipResult) {
            this.BuildShipResult = BuildShipResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PirateShipFactorySoapChannel : PirateShipConsumer.MyPirateShipFactory.PirateShipFactorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PirateShipFactorySoapClient : System.ServiceModel.ClientBase<PirateShipConsumer.MyPirateShipFactory.PirateShipFactorySoap>, PirateShipConsumer.MyPirateShipFactory.PirateShipFactorySoap {
        
        public PirateShipFactorySoapClient() {
        }
        
        public PirateShipFactorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PirateShipFactorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PirateShipFactorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PirateShipFactorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PirateShipConsumer.MyPirateShipFactory.BuildShipResponse PirateShipConsumer.MyPirateShipFactory.PirateShipFactorySoap.BuildShip(PirateShipConsumer.MyPirateShipFactory.BuildShipRequest request) {
            return base.Channel.BuildShip(request);
        }
        
        public PirateShipConsumer.MyPirateShipFactory.PirateShip BuildShip(string shipName) {
            PirateShipConsumer.MyPirateShipFactory.BuildShipRequest inValue = new PirateShipConsumer.MyPirateShipFactory.BuildShipRequest();
            inValue.Body = new PirateShipConsumer.MyPirateShipFactory.BuildShipRequestBody();
            inValue.Body.shipName = shipName;
            PirateShipConsumer.MyPirateShipFactory.BuildShipResponse retVal = ((PirateShipConsumer.MyPirateShipFactory.PirateShipFactorySoap)(this)).BuildShip(inValue);
            return retVal.Body.BuildShipResult;
        }
    }
}
