//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 7/28/2009 5:14:26 PM
namespace MvcTmpHlprs.Models
{
    
    /// <summary>
    /// There are no comments for AdventureWorksLT2008_DataEntities in the schema.
    /// </summary>
    public partial class AdventureWorksLT2008_DataEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new AdventureWorksLT2008_DataEntities object using the connection string found in the 'AdventureWorksLT2008_DataEntities' section of the application configuration file.
        /// </summary>
        public AdventureWorksLT2008_DataEntities() : 
                base("name=AdventureWorksLT2008_DataEntities", "AdventureWorksLT2008_DataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AdventureWorksLT2008_DataEntities object.
        /// </summary>
        public AdventureWorksLT2008_DataEntities(string connectionString) : 
                base(connectionString, "AdventureWorksLT2008_DataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AdventureWorksLT2008_DataEntities object.
        /// </summary>
        public AdventureWorksLT2008_DataEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AdventureWorksLT2008_DataEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<Product>("[Product]");
                }
                return this._Product;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Product> _Product;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorksLT2008_DataModel.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AdventureWorksLT2008_DataModel", Name="Product")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Product : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="productNumber">Initial value of ProductNumber.</param>
        /// <param name="standardCost">Initial value of StandardCost.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="sellStartDate">Initial value of SellStartDate.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Product CreateProduct(int productID, string name, string productNumber, decimal standardCost, decimal listPrice, global::System.DateTime sellStartDate, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.Name = name;
            product.ProductNumber = productNumber;
            product.StandardCost = standardCost;
            product.ListPrice = listPrice;
            product.SellStartDate = sellStartDate;
            product.rowguid = rowguid;
            product.ModifiedDate = modifiedDate;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ProductNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this.OnProductNumberChanging(value);
                this.ReportPropertyChanging("ProductNumber");
                this._ProductNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductNumber");
                this.OnProductNumberChanged();
            }
        }
        private string _ProductNumber;
        partial void OnProductNumberChanging(string value);
        partial void OnProductNumberChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this.ReportPropertyChanging("Color");
                this._Color = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Color");
                this.OnColorChanged();
            }
        }
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property StandardCost in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardCost
        {
            get
            {
                return this._StandardCost;
            }
            set
            {
                this.OnStandardCostChanging(value);
                this.ReportPropertyChanging("StandardCost");
                this._StandardCost = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StandardCost");
                this.OnStandardCostChanged();
            }
        }
        private decimal _StandardCost;
        partial void OnStandardCostChanging(decimal value);
        partial void OnStandardCostChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this.ReportPropertyChanging("ListPrice");
                this._ListPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListPrice");
                this.OnListPriceChanged();
            }
        }
        private decimal _ListPrice;
        partial void OnListPriceChanging(decimal value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this.ReportPropertyChanging("Size");
                this._Size = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Size");
                this.OnSizeChanged();
            }
        }
        private string _Size;
        partial void OnSizeChanging(string value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property Weight in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this.OnWeightChanging(value);
                this.ReportPropertyChanging("Weight");
                this._Weight = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Weight");
                this.OnWeightChanged();
            }
        }
        private global::System.Nullable<decimal> _Weight;
        partial void OnWeightChanging(global::System.Nullable<decimal> value);
        partial void OnWeightChanged();
        /// <summary>
        /// There are no comments for Property ProductCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this.ReportPropertyChanging("ProductCategoryID");
                this._ProductCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductCategoryID");
                this.OnProductCategoryIDChanged();
            }
        }
        private global::System.Nullable<int> _ProductCategoryID;
        partial void OnProductCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ProductModelID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ProductModelID
        {
            get
            {
                return this._ProductModelID;
            }
            set
            {
                this.OnProductModelIDChanging(value);
                this.ReportPropertyChanging("ProductModelID");
                this._ProductModelID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductModelID");
                this.OnProductModelIDChanged();
            }
        }
        private global::System.Nullable<int> _ProductModelID;
        partial void OnProductModelIDChanging(global::System.Nullable<int> value);
        partial void OnProductModelIDChanged();
        /// <summary>
        /// There are no comments for Property SellStartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime SellStartDate
        {
            get
            {
                return this._SellStartDate;
            }
            set
            {
                this.OnSellStartDateChanging(value);
                this.ReportPropertyChanging("SellStartDate");
                this._SellStartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SellStartDate");
                this.OnSellStartDateChanged();
            }
        }
        private global::System.DateTime _SellStartDate;
        partial void OnSellStartDateChanging(global::System.DateTime value);
        partial void OnSellStartDateChanged();
        /// <summary>
        /// There are no comments for Property SellEndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> SellEndDate
        {
            get
            {
                return this._SellEndDate;
            }
            set
            {
                this.OnSellEndDateChanging(value);
                this.ReportPropertyChanging("SellEndDate");
                this._SellEndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SellEndDate");
                this.OnSellEndDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _SellEndDate;
        partial void OnSellEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSellEndDateChanged();
        /// <summary>
        /// There are no comments for Property DiscontinuedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DiscontinuedDate
        {
            get
            {
                return this._DiscontinuedDate;
            }
            set
            {
                this.OnDiscontinuedDateChanging(value);
                this.ReportPropertyChanging("DiscontinuedDate");
                this._DiscontinuedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DiscontinuedDate");
                this.OnDiscontinuedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DiscontinuedDate;
        partial void OnDiscontinuedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDiscontinuedDateChanged();
        /// <summary>
        /// There are no comments for Property ThumbNailPhoto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ThumbNailPhoto
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._ThumbNailPhoto);
            }
            set
            {
                this.OnThumbNailPhotoChanging(value);
                this.ReportPropertyChanging("ThumbNailPhoto");
                this._ThumbNailPhoto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThumbNailPhoto");
                this.OnThumbNailPhotoChanged();
            }
        }
        private byte[] _ThumbNailPhoto;
        partial void OnThumbNailPhotoChanging(byte[] value);
        partial void OnThumbNailPhotoChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailPhotoFileName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailPhotoFileName
        {
            get
            {
                return this._ThumbnailPhotoFileName;
            }
            set
            {
                this.OnThumbnailPhotoFileNameChanging(value);
                this.ReportPropertyChanging("ThumbnailPhotoFileName");
                this._ThumbnailPhotoFileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThumbnailPhotoFileName");
                this.OnThumbnailPhotoFileNameChanged();
            }
        }
        private string _ThumbnailPhotoFileName;
        partial void OnThumbnailPhotoFileNameChanging(string value);
        partial void OnThumbnailPhotoFileNameChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this.ReportPropertyChanging("rowguid");
                this._rowguid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rowguid");
                this.OnrowguidChanged();
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
    }
}
